#!/bin/bash

name=${0##*/}
e_path=${0%/*}
s_path=$(pwd)

#echo 'bash-script_name:    '$name
#echo 'bash-script_path:    '$e_path
#echo 'bash-execution_path: '$s_path

python3 ~/bin/.commands/engine.py $e_path $s_path $name $@
